### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by jeremiah-gaiser** [INFO-526-S24/project-final-InsightArchitect#1]
The following is the peer review of the project proposal by Viz Wizards. The team members that participated in this review are 

- Nick Ferrante - @n-ferrante
- Jasdeep Singh Jhajj - @Jasdeep-Singh-Jhajj
- Agastya Deshraju - @AgastyaDeshraju
- Gillian McGinnis - @gmcginnis
- Tanya Evita George - @tanyageorge
- Jeremiah Gaiser - @jeremiah-gaiser
- Mrunal Jadhav - @mrunal0699

-----------
### Describe the goal of the project.

Assess the provided global poverty dataset and identify which countries are effectively combating poverty and which indicators are useful correlates of poverty,.

-----------
### Describe the data used or collected.

Our World in Data dataset on poverty. Provides population and poverty data on the basis of country and year. 

-----------
### Describe how the research question will be answered, e.g. what approaches / methods will be used.

Information regarding poverty distributions, percentages, and inequality metrics will be visualized using time series, ridge plots, and an interactive 3D globe and parallel coordinate plot. The interactivity serves the purpose of providing the users with further exploration of trends and outliers allowing the user to discover relationships between poverty and economic changes and policies.

Additional data on education and other factors will be brought in and correlated with poverty levels to identify what factors correspond most strongly to poverty.

-----------
### Is there anything that is unclear from the proposal?

Mention is made of assessing how different factors affect poverty outcomes, but specific additional datasets are not mentioned. Do you intend to bring in additional data? What and where where will that come from? 

Similarly for the dependency columns to answer question 2, the columns are not clearly separated, so some punctuation might be needed.

-----------
### Provide constructive feedback on how the team might be able to improve their project.

The 'Introduction' is mostly about the dataset, and is followed by the section 'Why we are choosing this dataset?' which retreads the same territory. Perhaps the intro should be more generally about the topic, so as to motivate the use of the dataset, to be described in the next section.

The "Description of an Idea" header should be more specific, and the section reads more like a brainstorm than a fleshed out idea. 

The dependency column for question 2 could use proper sentences / improved formatting.

-----------
### What aspect of this project are you most interested in and would like to see highlighted in the presentation.

We are excited about the 3D visualization! One thing to keep in mind is that 3D has unique challenges, e.g. not being able to visualize all the data at one time. We look forward to seeing how you tackle these challenges.  

-----------
### Provide constructive feedback on any issues with file and/or code organization.

At the top, using library(tidyverse, png) will not work properly; to load multiple libraries, must either be split as library(tidyverse) // library(png) , etc, or loaded via pacman as in homework.

Dataset glimpse is commented out (was this intentional?)

Timeline needs a header to be in the sidebar; right now, it's a sub-header of Q2

Proposal description needs to be added to top (YAML)

Dataset & Dataset Description can be lumped into one section

'References' is empty.

-----------
### (Optional) Any further comments or feedback?

Nice work! We're looking forward to seeing what insights you glean. :)

**Comment by ayeshakhatunsujana** [comment]
Thank you for the feedback. 

As you have mentioned that, how different factors affect poverty outcomes? and solve this will we use additional dataset? actually we will only use one dataset which is large enough and it has thousand of data, so we don't need additional dataset. 
According to your suggestion we will recheck the question 02. We will update the our motivation about choosing this dataset, references and other things you have mentioned. Once again thank you so much to your team. 

Best Regards

InsightArchitect
