### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by MikiKatyal** [INFO-526-S24/project-final-InsightArchitect#2]
The following is the peer review of the project proposal by [VizMasters]. The team members that participated in this review are

[Kondapaneni Siva Rohit ] - @[Sivarohitk]

[Rohit Vatsava Kalakala] - @[Rohit-Vatsava]

[Miki Katyal] - @[MIKIKATYAL]

[Ajay Kumar] - @[AjaykATgithub]

[Surya Vardhan Dama] - @[suryavardhandama]

[Monica Tejaswi Kommareddy] - @[KommareddyMonicaTejaswi]

- Describe the goal of the project.
 a.) Analyze the poverty data to find the relationship of different factors effecting the poverty.

- Describe the data used or collected.
a.) One single data file "pip_dataset.csv" is being used with about more than 4500 rows and 108 columns. This data has information about 
1. countries 
2. years
3. survey data for headcount living under 10$ per day
4. Shortfall from poverty line of 10$ per day.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
a.) The research question is being answered by analyzing the time series data on the poverty. They will use Ridge plots, Dynamic 3D Globe and PCP , to show the visualization for the source data.

- Is there anything that is unclear from the proposal?
a.) Dataset Description - Dimension section say there are 108 columns where as the "code book insight" section says there are only 10 columns.
b.) Question 1 : What is the source or basis of taking as 2.15 USD as the reference for stating this number as a benchmark in context of poverty definition. Is this number defined by any international body or entity and in what context is it mentioned.
c.) Question 1 : Analysis Plan  : Language is unclear " We will be used the time ...."
d.) Question 1 : Analysis Plan : Plots are mentioned for Q1 Part 1 but no information about what plots will be used for part 2.
e.) Question 1 and 2  : The significance of Question : The language used in not easy to understand for a layman (with no background in finance or economics. )
f.) Question 2 : Dependency columns : Column names are unclear.

- Provide constructive feedback on how the team might be able to improve their project.
a.) Question 2 : Analysis Plan : Second para about visualization , interactivity and insides can be written as bullet points to get a better readability.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
a.) About the visualization to show the said relationships and how will the visualization appear in Dynamic 3D Globe and PCP.

- Provide constructive feedback on any issues with file and/or code organization.
a.) Purpose of having the dataset section above introduction is unclear.
b.) Setup code block is not required in the proposal render.

- (Optional) Any further comments or feedback?

**Comment by ayeshakhatunsujana** [comment]
Thank you for the feedback. 
As you have mentioned that, We have some writing mistakes in the proposal, and some modification needed in Question 01 and Question 02. We will consider your feedbacks and will change it accordingly. 
Thank you so much for you constructive feedback. 

Best Regards

Insight Architect
