### ISSUE TITLE
Code peer review

### ISSUE THREAD

**Issue by gmcginnis** [INFO-526-S24/project-final-InsightArchitect#4]
The following is the peer review of the project code by VizWizards. The team members that participated in this review are 

- Nick Ferrante - @n-ferrante
- Jasdeep Singh Jhajj - @Jasdeep-Singh-Jhajj
- Agastya Deshraju - @AgastyaDeshraju
- Gillian McGinnis - @gmcginnis
- Tanya Evita George - @tanyageorge
- Jeremiah Gaiser - @jeremiah-gaiser

---

#### 1. Purpose of Code
- [x] #5
- [ ] Ambiguous or unclear

---

#### 2. Code Quality

- [x] Code is clean, readable, and well-organized
- [x] Adequate comments explaining complex or tricky code sections
- [x] Variables, methods, and classes have meaningful names
- [x] Consistent code style (indentation, naming conventions, etc.)

---

#### 3. Documentation

- [ ] Code documentation (e.g., comments) is sufficient
- [ ] Readme or other documentation updated if necessary

---

#### 4. Best Practices

- [x] No hardcoded values; constants used appropriately
- [x] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [ ] Code avoids repetition and promotes reusability

---

#### 5. Additional Comments

- Please provide feedback, areas of improvement, or other observations.

There are a few spaces (e.g., when listing `labs()`) where the indentation is slightly off within the list (e.g., line 122), but otherwise the indentation is very consistent.

For commit messages it would be good to be a bit more specific about what changes are being made (e.g., instead of 'Q1 update', state what updates are being done).

The main README should be updated with a brief overview of the repo/project. The code folder needs an updated README with cookbook for each set.

The same .csv files are re-read multiple times (310 & 351).

The gif-creation chunk (and some plot-saving chunks) are set to echo=F and have a (commented out) save section, but needs `eval=F` in order to avoid re-running at every site render/update.

---

#### 6. Recommendation

- [ ] Approved - ready to be merged
- [x] Approved with minor issues - can be addressed later
- [ ] Requires changes - provide feedback and request another review

---

**Comment by ayeshakhatunsujana** [comment]
Dear team VizWizards,
The repository organization has already been added to the index.qmd file for the documentation. Readme has already been updated. We appreciate your alert, and we will soon include the cookbook. Removing the re-read.csv file several times is what you suggested. To make the comments easier to comprehend for users who are not familiar with them, we made some modifications. We sincerely appreciate your insightful input, VizWizards team.

Best 
InsightArchitect Team
