### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by AgastyaDeshraju** [INFO-526-S24/project-final-InsightArchitect#7]
The following is the peer review of the Presentation proposal by VizWizards. The team members that participated in this review are 

- Nick Ferrante - @n-ferrante
- Jasdeep Singh Jhajj - @Jasdeep-Singh-Jhajj
- Agastya Deshraju - @AgastyaDeshraju
- Gillian McGinnis - @gmcginnis
- Tanya Evita George - @tanyageorge
- Jeremiah Gaiser - @jeremiah-gaiser
- Mrunal Jadhav - @mrunal0699

- Content: Is the research question well designed and is the data being used relevant to the research question?
The research questions were well designed and they had a few interesting ideas that they wanted to tackle. The data they used was relevant to the research questions.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
The visualization showing both the mean and median was a little confusing. Better legends could also be used for the heatmap as it is a little tough to understand as of now. The animation for the first bar plot also seemed extraneous, and the x-axis would benefit from rotating the labels.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
The project was clearly carefully thought out, and the research questions that they aimed to answer were selected well. 

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
The slides are well organized and readable, but they could benefit from using a little less text in them. The use of bolding to highlight key features was good. The plots could use slightly larger labels and legends.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
The team presented very well and had a great introduction. It was evident that all members contributed towards the project.

**Comment by ayeshakhatunsujana** [comment]
Dear VizWizards Team, 
Thank you for the honest feedback and nice observations. We will try to enlarged the size of the plots. 

Best 
Ayesha 
Insight Architect Team
