### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by Sivarohitk** [INFO-526-S24/project-final-InsightArchitect#8]
The following is the peer review of the Presentation proposal by VizMasters. The team members that participated in this review are 

[Kondapaneni Siva Rohit ] - @[Sivarohitk]

[Rohit Vatsava Kalakala] - @[Rohit-Vatsava]

[Miki Katyal] - @[MIKIKATYAL]

[Ajay Kumar] - @[AjaykATgithub]

[Surya Vardhan Dama] - @[suryavardhandama]

[Monica Tejaswi Kommareddy] - @[KommareddyMonicaTejaswi]
- ...

- Content: Is the research question well designed and is the data being used relevant to the research question?

   yes, research questions are well designed and it covered interesting topics and data selected was aligned with research questions

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

   yes, they use appropriate visualization but they should use better legends for heat maps, other than that its good 

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

   The project was clearly well-planned, and the research questions chosen were appropriate and thoughtful.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

   yes, slides are well organized and readable 
 

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

  yes, they presented their project very well, they had great introduction and everyone did well

**Comment by ayeshakhatunsujana** [comment]
Thank you so much for your feedback!
